### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by diegocgaona** [trinker/sentimentr#10]
Hi @trinker ,

I want to make a sentiment analysis tool for Facebook comments, and your package seems very nice.
But, I can analyse text in portuguese, if I have a dictionary with positive/negative words?

Thanks!!

**Comment by trinker** [comment]
I think the answer is "it depends".  This package was definitely designed with English language structures in mind.  It also deals with negators and amplifiers as well.  I don't know what the euivalents of these types are in Portuguese.   If you're looking for something that works with just a negative and positive dictionary I think the [syuzhet](http://www.matthewjockers.net/2015/02/02/syuzhet) package may be a better choice here.

**Comment by diegocgaona** [comment]
Thanks for you @trinker!
I will study the options :)
