### ISSUE TITLE
Crowdflower Self Driving Cars Dataset contains UTF-8 error text

### ISSUE THREAD

**Issue by Shantanu1497** [trinker/sentimentr#100]
Hey @trinker , trying to use the Self Driving Cars dataset - this is what it looks like right now

![screenshot 2019-01-09 at 5 19 13 pm](https://user-images.githubusercontent.com/29790185/50897708-f00fd300-1432-11e9-9c24-35ad176633ee.png)

**Comment by trinker** [comment]
Thanks for the catch.  Fixed it.
