### ISSUE TITLE
highlight issue

### ISSUE THREAD

**Issue by kenmcgarry** [trinker/sentimentr#104]
Hi Thanks for this great package.

I've upgraded from sentimentr V2.6.1 to V 2.7.1 and one of the simpler examples I use no longer works. The more complicated examples you provide seem to work fine. 

```
'My life has become terrible since I started work.' %>%
  sentiment_by(by = NULL) %>%
highlight()
```

```
Error in `[.data.table`(y, , list(sentiment = attributes(x)[["averaging.function"]](sentiment),  : 
  attempt to apply non-function 
```

**Comment by trinker** [comment]
Thank you kindly for reporting. I can replicate. I'm guessing something simple.

**Comment by trinker** [comment]
@kenmcgarry Thanks for the feedback.  Fixed now.  Give it a try.

**Comment by kenmcgarry** [comment]
Thanks, will do.

Ken

**Comment by zong-you** [comment]
Hi, I am using sentimentr V2.7.1 and am experiencing the same error as Ken.

mytext <- c(
  'do you like it?  But I hate really bad dogs',
  'I am the best friend.',
  'Do you really like it?  I\'m not a fan'
)
write.csv(mytext, "mytext.csv")

mytext2 <- read.csv("mytext.csv")
mytext2 %>%
  get_sentences() %>%
  sentiment_by() %>%
  highlight()

Error in `[.data.table`(y, , list(sentiment = attributes(x)[["averaging.function"]](sentiment),  : 
  attempt to apply non-function

**Comment by zong-you** [comment]
Hi, I am using sentimentr V2.7.1 and am experiencing the same error as Ken when I use read.csv.

```
mytext <- c(
'do you like it? But I hate really bad dogs',
'I am the best friend.',
'Do you really like it? I'm not a fan'
)
write.csv(mytext, "mytext.csv")

mytext2 <- read.csv("mytext.csv")
mytext2 %>%
get_sentences() %>%
sentiment_by() %>%
highlight()

```
```
Error in [.data.table(y, , list(sentiment = attributes(x)["averaging.function"], :
attempt to apply non-function
```

**Comment by trinker** [comment]
You need 2.8.0

**Comment by zong-you** [comment]
Yes version 2.8.0 does not have this issue. Thanks for your reply. 

For the benefit of other users, you can download the latest version from Github using the following code:
`install_github("trinker/sentimentr")`
