### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘textshape’

### ISSUE THREAD

**Issue by xhaj06** [trinker/sentimentr#105]
Hi i downloaded your scripts, followed tutorial and its said this:
Error in loadNamespace(name) : there is no package called ‘textshape’

**Comment by trinker** [comment]
it should have installed textshape (depending on how you tried to install
sentimentr).  Try install.packages('textshape') first

**Comment by xhaj06** [comment]
I installed all packages mentioned https://cran.r-project.org/web/packages/sentimentr/index.html and it works. Thx, its interesting tool. 
btw: its interesting that it can even work with multi-sentenses phrases. I tried break down "

Director   Paul Matthews, who also wrote/directed the weak 1995 monster movie   "Grim", clearly doesn't know how to pace his films."

 into several small sentences, the results is similar but not same...interesting...really nice work.
