### ISSUE TITLE
You need 2.8.0

### ISSUE THREAD

**Issue by MsPhotonUIUC** [trinker/sentimentr#106]
You need 2.8.0 

_Originally posted by @trinker in https://github.com/trinker/sentimentr/issues/104#issuecomment-497342674_

Hello! I've been having a lot of fun with this new package. 

I've encountered the same error in my highlight line, however when I used the 'install.package()' prompt to update, it will only go to 2.7.1. (Checking with old.packages() says its up-to-date.) Can I prompt it to go to 2.8? 

(first time asking a question on Github so I'm not sure if this is the right place to post it)

**Comment by zong-you** [comment]
Hi, you can download the latest version from Github using the following code. 

`install_github("trinker/sentimentr")`

**Comment by RoguePower** [comment]
Nope does not solve it, updates to 2.7.1
