### ISSUE TITLE
Sentiment Score Seems Incorrect

### ISSUE THREAD

**Issue by jaclynmize** [trinker/sentimentr#113]
Can you explain why the following sentences (which all seem positive) were given a negative score using this package? 

**Sentence | SentimentR (Current Package)**
Great boost of energy without a nasty crash afterwards | -0.25
My lips have never looked or felt better | -0.2828427
It is absolutely perfect no play in blade gorgeous to look at and hold extremely solid | -0.05
No gaps perfectly centered blade geometrical cemetrical grind on both sides | -0.2261335
It was a nice clean smell not floral or fruity | -0.1897367

**Comment by trinker** [comment]
You can dive into the documentation for how the algorithm works.  Most any algorithm is not 100% accurate.  How does the algorithm do overall on a random sample?
