### ISSUE TITLE
Question about 'highlight'

### ISSUE THREAD

**Issue by GabriellaS-K** [trinker/sentimentr#121]
Hi, 

Is there a way to open the highlighted text in an excel rather than HTML? Also is there a way to show it with other columns, for example, I am using question responses, and IDs. The question responses are highlighted, and I would like to have the ID by the highlighted response so I can compare.

Many thanks for a great package!

**Comment by trinker** [comment]
> Is there a way to open the highlighted text in an excel rather than HTML?

Not currently with this package but you could tear apart the source code and extend it accordingly.

> Also is there a way to show it with other columns, for example, I am using question responses, and IDs. The question responses are highlighted, and I would like to have the ID by the highlighted response so I can compare.

You could use `sentiment_by()` and include both columns in the `by` argument.
