### ISSUE TITLE
Transparency for lexicon::hash_sentiment_jockers_rinker

### ISSUE THREAD

**Issue by GabriellaS-K** [trinker/sentimentr#125]
In the news file it says: 
```
NEW FEATURES

The default sentiment sentiment lookup table used within sentimentr is now lexicon::hash_sentiment_jockers_rinker, a combined and augmented version of lexicon::hash_sentiment_jockers (Jockers, 2017) & Rinker's augmented lexicon::hash_sentiment_huliu (Hu & Liu, 2004) sentiment lookup tables.
```

I'm looking for some transparency and information on lexicon::hash_sentiment_jockers_rinker. How were the two lexicons combined, please?

**Comment by trinker** [comment]
I don't recall but you can go to the lexicon package and compasre `lexicon::hash_sentiment_jockers` (Jockers, 2017) & Rinker's augmented `lexicon::hash_sentiment_huliu` (Hu & Liu, 2004) usinf anti joins on the words to see how they differ.  Closing as this doesn't appear to be a code based issue.
