### ISSUE TITLE
I wonder why this sentence is recognized as positive

### ISSUE THREAD

**Issue by dogonanisland** [trinker/sentimentr#127]
I wonder why this sentence is recognized as positive.

> sentiment('I did not like how it was boring')
   element_id sentence_id word_count sentiment
1:                1                  1                  8 0.1767767

**Comment by trinker** [comment]
Beause the 'not' was also associated witht he 'boring' window.  Here we take n.before from 5 down to 4:

```
sentiment('I did not like how it was boring', n.before = 4)
##    element_id sentence_id word_count  sentiment
## 1:          1           1          8 -0.5303301
```

**Comment by dogonanisland** [comment]
Thanks for getting back to me. I see the effect of n.before. I have a bunch
of texts like these clause sentences (students' responses to an open-ended
item on a survey). What is the best way to conduct the sentence-level
sentiment analysis? Do I have to set up n.before (n.after for certain
cases) each sentence at a time?

Thanks,
Atsushi Miyaoka
