### ISSUE TITLE
Add terms

### ISSUE THREAD

**Issue by trinker** [trinker/sentimentr#14]
# Amplifiers

```
update_key(valence_shifters_table, x = data.frame(x = c("exceedingly", "remarkably", "especially"), y = c(2, 2, 2)))
```
# Negatives

```
update_key(valence_shifters_table, x = data.frame(x = c("excessively", 'overly', 'unduly', 'too much', 'too many', 'too often', 'I wish', 'too good', 'too high', 'to tough'), y = c(rep(-2, 8), rep(-1, 2))))
```

**Comment by trinker** [comment]
```
valence_shifters <- update_key(sentimentr::valence_shifters_table, drop=NULL, 
    x = data.frame(
        x = c("exceedingly", "remarkably", "especially"), 
        y = c(2, 2, 2), stringsAsFactors = FALSE
    ), 
    comparison=sentimentr::polarity_table, 
    sentiment=F
)

polarity_table <- update_key(sentimentr::polarity_table, 
    x = data.frame(
        x = c("excessively", 'overly', 'unduly', 'too much', 'too many', 'too often', 'I wish', 'too good', 'too high', 'to tough'), 
        y = c(rep(-2, 8), rep(-1, 2))
    )
)
```

**Comment by fahadshery** [comment]
Hi,

I added few terms to `valence_shifters_dt` but can't seem to specify the new `data.table`.
Here is the code:

`valence_shifters_dt <- read_csv("~/GCE/Text Analytics/valence_shifters_dt_v1_use_this.csv")`

`Error in sentiment.get_sentences_character(., polarity_dt = bt_sentiment_hash, : `polarity_dt` & `valence_shifters_dt` not mutually exclusive`

Also tried: 

`valence_shifters_dt <- read_csv("~/GCE/Text Analytics/valence_shifters_dt_v1_use_this.csv")`

`update_key(sentimentr::valence_shifters_dt, x = valence_shifters_dt)`

but getting error:

`Error in is_key(key, sentiment = sentiment) : 'valence_shifters_dt' is not an exported object from 'namespace:sentimentr'`
