### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by cschwem2er** [trinker/sentimentr#15]
Hi,

first of all thanks a lot for writing this R package! I'm currently experimenting with political texts and really like it so far.

Is it also possible to use `sentimentr` with languages other than english, maybe by  enabling the use of custom dictionaries?

**Comment by trinker** [comment]
Did you read the documentation?

**Comment by trinker** [comment]
Have a look at `?as_key` but it may not function the same on other languages.  The algorithm was written with English in mind.
