### ISSUE TITLE
Consider adding 'unprofessional' to main dictionary

### ISSUE THREAD

**Issue by trinker** [trinker/sentimentr#19]
A negative score

**Comment by trinker** [comment]
Also add 'totally' as an amplifier

**Comment by GabriellaS-K** [comment]
How can I get a list of all the words in the dictionary that sentimentr uses, so that I can update/edit it? In my dataset I have 'tender' but in this context it refers to tender-pain, and thus is negative, so I need to update the dictionary used. 

Many thanks
