### ISSUE TITLE
Error using highlight original.text parameter

### ISSUE THREAD

**Issue by carlsonp** [trinker/sentimentr#20]
I'm getting an error when using the `original.text` parameter of the `higlight()` method.

```
    highlight(temp_sentiment, file = file.path("highlighted", paste(prod, "_highlighted-text.html", sep = "")), original.text = filtered[['Description']], open = FALSE)
```

```
Error in `[[<-.data.frame`(`*tmp*`, "txt", value = c("Feedback: \nAR - Goal History/Diagnostic Report....",  : 
  replacement has 3649 rows, data has 3658
```

I've tried debugging and I think the problem may be around line [50 of Highlight.R](https://github.com/trinker/sentimentr/blob/master/R/highlight.R#L50)

```
if (!is.null(original.text)){
        txt <- get_sentences2(original.text)
    } else {
        txt <- get_sentences(x)
    }

    y[["txt"]] <- unlist(txt)

    y[, txt := ifelse(polarity == "", txt, sprintf("<mark class = \"%s\">%s</mark>", polarity, txt))]
```

If I set `original.text` to `NULL` (as is the default), it works fine.  I'm not quite sure why there's a size difference.

I also tried setting `missing_value=NULL` for the `sentiment_by` call but that didn't change anything.

Do you have any suggestions?  Thanks.

**Comment by trinker** [comment]
Thanks for the report.  I want to adress this but without the data to
replicate this is not possible.

Can you narrow down the data set using the rule of halves to isolate what
in the data is triggering the problem?  See section 5 of this document for
debugging the data:
https://cran.r-project.org/web/packages/qdap/vignettes/cleaning_and_debugging.pdf

**Comment by carlsonp** [comment]
Thanks.  I was able to fix one processing portion.  I ended up needing to remove all quotations `"` in the text.  However, I've come across the following minimal example which doesn't appear to work:

```
test = "Test student settings quizzing allowed....forward: need it for individual students not classes...said  I would forward"
temp_sentiment = sentiment_by(test)
highlight(temp_sentiment, original.text = test, open = FALSE)
```

```
Error in `[[<-.data.frame`(`*tmp*`, "txt", value = c("Test student settings quizzing allowed....forward: need it for individual students not classes...",  : 
  replacement has 2 rows, data has 3
```

There's no special characters or encoding issues so I wonder if perhaps it's getting hung up on the multiple periods?  Maybe it's having trouble parsing the sentences?  It's interesting because the sentiment call seems to work fine, it's just the highlight where there's an error.

**Comment by trinker** [comment]
Thanks for the report.  I think I have it fixed.  Testing shows so:

```
test = "Test student hate settings quizzing allowed....forward: need it for love individual students not classes...said  I would forward"
temp_sentiment = sentiment_by(test)

highlight(temp_sentiment, original.text = test)
```

Don't hesitate to reopen or open a new issue if you encounter additional problems.
