### ISSUE TITLE
Valence category 4 is missing

### ISSUE THREAD

**Issue by rtw30606** [trinker/sentimentr#23]
The documentation is missing any mention of conjunctions (4) in the description of the type of valence shifter words.

**Comment by trinker** [comment]
Thanks for the catch.  I'll take care of this in the next update.

**Comment by trinker** [comment]
Compliments of Richard Watson to include in the documentation
  ![image](https://cloud.githubusercontent.com/assets/1763278/20107700/754f5218-a5a7-11e6-8a3d-01cf2334b521.png)
