### ISSUE TITLE
Issue with bi- gram or more in Polarity table

### ISSUE THREAD

**Issue by prudhviraju535** [trinker/sentimentr#25]
Hi, I am using Sentimentr and Qdap package for polarity scoring on text data. what i observed is, when i use bi gram or more in polarity table, which i created separately for polarity scoring,  sentimentr is not giving any polarity score but QDAP is able to score it. 

could you please help me how to modify for sentimentr package. i want to use sentimentr  its faster then QDAp. i am also converting Polarity table to as.key  for usage.

**Comment by trinker** [comment]
Please provide a reproducible example.

**Comment by prudhviraju535** [comment]
Hi,

require(sentimentr)
require(qdap)


## Texts
mytext <- c(
  "hopefully wallet will comeback",
  "excelente",
  "duplicate photo finder",
  "Thanks Staff!",
  "limit your sentence"
)

## Polarity table
set.seed(10)
key <- data.frame(
  words = c("excelente","limit","duplicate photo finder","wallet will comeback","thanks"),
  polarity = c(1,-1,-1,-1,1),
  stringsAsFactors = FALSE
)

mykey <- as_key(key)

striptext=function(x){
  x=removePunctuation(stripWhitespace(tolower(x)))  }


text=as.character(striptext(mytext))
text=replace_number(text)
text=replace_emoticon(text,emoticon_dt = sentimentr::emoticons)
text=replace_grade(text, grade_dt = sentimentr::grades)


## Sentimentr polarity

Sentir=sentiment_by(text,mykey,valence_shifters_dt = valence_shifters_table,by=NULL,
                  amplifier.weight = 3, n.before = 5, n.after = 3
                  ,question.weight = 2, but.weight = 0.85, missing_value = 0)


## Qdap Polarity
QDAPoutput=counts(polarity(striptext(mytext),polarity.frame = mykey,
                                       constrain = F,negators = qdapDictionaries::negation.words,
                                       amplifiers = qdapDictionaries::amplification.words,
                                       deamplifiers = qdapDictionaries::deamplification.words,
                                       question.weight = 3, amplifier.weight = 2,
                                       n.before = 5, n.after = 3))[, "polarity"]


##  Final output
outp=cbind(Sentir,QDAPoutput)

**Comment by prudhviraju535** [comment]
If u check the final output "outp", Sentimentr is not scoring but Qdap does.

**Comment by trinker** [comment]
I believe you need to name the argument to `sentiment_by` as the second argument to this function is not the polarity table as you assume, `polarity_dt =mykey`

**Comment by prudhviraju535** [comment]
Hi .. i changed it to Sentiment . its working .. Thanks.. 

But it shows this warning : 

Warning message:
In `[.data.table`(dat[, `:=`(indx, wc < 1), by = c("id", "sentences",  :
  with=FALSE ignored, it isn't needed when using :=. See ?':=' for examples.

**Comment by trinker** [comment]
You need the latest version from github.  A change in data.table.  If you don't feel like updating the warning message can be ignored.
