### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by trinker** [trinker/sentimentr#38]
stringi is likely to do OS indepen. conversion of (escape sequence) bytes to unicode (or something like that) that can then be used to look up the emoji name.  Use the reqex to pull them out.

then use Unicode package to go the rest of the way `u_char_name(as.u_char('U+2702'))`

**Comment by trinker** [comment]
https://github.com/gagolews/stringi/issues/262

**Comment by cschwem2er** [comment]
Hi,
first of all thanks for this awesome package! I'm currently using it to get sentiments for billions of youtube comments. Are there any updates on the use of emojis? Especially for social media texts this would be a big deal.

**Comment by trinker** [comment]
Not currently...waiting on the stringi update icu to  higher version
