### ISSUE TITLE
String Length Limit

### ISSUE THREAD

**Issue by statspro1** [trinker/sentimentr#40]
I am wondering if someone has encountered the following error in the past:

```
Error in sprintf(paste("%-", Q, "s", sep = ""), col) : 
  required resulting string length 31315 is greater than maximal 8192 
```
A workaround is appreciated.

**Comment by trinker** [comment]
Without the context this is nearly impossible to debug.  Can you provide the code you ran to get the error.  Right now I don't even know what function caused this, though I suspect it was the hilight command.

**Comment by trinker** [comment]
I'm closing this per no response from the original poster.  Feel free to reopen
