### ISSUE TITLE
Incorrect number of word calculations

### ISSUE THREAD

**Issue by sivaram10** [trinker/sentimentr#42]
sentiment_attributes("Assisted Local yy on resolving mm ll jj ll upgrade issues.  He created a ww qq process for V. xx and tt gg.")[1]
![image](https://cloud.githubusercontent.com/assets/10365458/26456881/6e945118-413c-11e7-9aa6-09a45a12f2d1.png)

str_count("Assisted Local yy on resolving mm ll jj ll upgrade issues.  He created a ww qq process for V. xx and tt gg.","\\S+")
![image](https://cloud.githubusercontent.com/assets/10365458/26456899/7c0f7d4a-413c-11e7-945b-6b4a77b64f55.png)

**Comment by trinker** [comment]
@sivaram10 thanks

Yes 34 is wrong.  It's in the `termco::token_count`.  I'll look into within a day and isolate the problem.  Note that 23 is incorrect as well.  There are 23 words but 26 tokens (words and letters)

**Comment by trinker** [comment]
Thanks for the spot.  The output now gives:

```
> sentimentr::sentiment_attributes("Assisted Local yy on resolving mm ll jj ll upgrade issues. He created a ww qq process for V. xx and tt gg.")[1]
$Meta
       Stat  n
1     words 23
2    tokens 26
3 sentences  2
4 questions  0
```
