### ISSUE TITLE
Depends:	R (≥ 3.1.0) Not working on 3.2.3

### ISSUE THREAD

**Issue by Mavericks334** [trinker/sentimentr#43]
Hi,

The R version for this to work says Depends: | R (≥ 3.1.0). However when i try to load the package after installing it. This is the error i get.

> library(sentimentr)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘textclean’
In addition: Warning message:
package ‘sentimentr’ was built under R version 3.4.1 
Error: package or namespace load failed for ‘sentimentr’

Is this an error or  in the code or the page has not been updated to say only it works for R >3.4

Regards,
Ren.

**Comment by trinker** [comment]
Thanks for the spot. Minimal version has not been updated.  Make the pull request if you feel comfortable doing so.

**Comment by Mavericks334** [comment]
Hi,

I am new to this. Could you let me know what do i need to do to pull request and do i need to make any changes like installing the zip file.

Regards,
Ren.

**Comment by trinker** [comment]
Nice this is a pretty easy way to get involved.  You can do the pull request in one of two ways.  Either fork it, make the change, push it, and then a pull request OR do it by editing the file on GitHub and the pull request will be created.  The later approach is easier but you may want practice doing the first one.  

In any event the file that needs to be changed is the DESCRIPTION file...edited to have the correct minimal version of R.

**Comment by trinker** [comment]
@Mavericks334 Any progress with this?

**Comment by Mavericks334** [comment]
Unfortunately could not figure it out

**Comment by trinker** [comment]
did you install sentimentr from GitHub or CRAN?

**Comment by Mavericks334** [comment]
From Cran

**Comment by trinker** [comment]
Thanks...one more question: what version of R were you using?

**Comment by Mavericks334** [comment]
3.2.3 was the version

**Comment by trinker** [comment]
can you try installing textshape from source first:

```
install.packages('textshape', type = 'source')
```

**Comment by Mavericks334** [comment]
Sure would do so. Also I have upgraded to 3.4 it works there

**Comment by AdityaJakkam** [comment]
Thanks @trinker , installing 'textshape' helped me in the newer version of RStudio.
