### ISSUE TITLE
Move sentence splitting out of the function

### ISSUE THREAD

**Issue by trinker** [trinker/sentimentr#46]
sentence splitting will be moved outside of the `sentiment` function and handled by an reimport from `textshape::split_sentence`.  The `sentiment` and `sentiment_by` functions will give a  warning if the object is not a sentence_split object (class may need to be added in the reimport).

This will:

1.  Make it easier to maintain sentence splitting
1. Speed up sentiment classifying
1. Reduce redundant splitting for different functions (or same function call twice) using the same text

Be careful to do this to all functions that use sentence splitting such us hilighting and word extraction.  This is a justifiable breaking change that will bump the major version.

**Comment by trinker** [comment]
Makes https://github.com/trinker/sentimentr/issues/44 a moot point

**Comment by trinker** [comment]
Below shows the memory consumption for sentiment function parts:

![image](https://user-images.githubusercontent.com/1763278/28629273-f9d7e454-71f4-11e7-861f-b819e992bb97.png)

**Comment by MarcoDVisser** [comment]
What does a targetedSummary reveal on the most intensive line?

https://www.rdocumentation.org/packages/aprof/versions/0.3.2/topics/targetedSummary

**Comment by trinker** [comment]
make sure a mutate function passes on the vector to the data frame

**Comment by trinker** [comment]
@MarcoDVisser not sure as I haven't run the unction but will..this change is more for maintainability but may be useful for memory consumption though sentence splitting isn't the biggest memory hog in the function

**Comment by trinker** [comment]
Make sure it interacts with `uncombine` as expected

**Comment by trinker** [comment]
make `senteiment_by.senteiment_by` handle character vect for `by` to be consistent

**Comment by trinker** [comment]
also correct readme

**Comment by trinker** [comment]
- uncombine, highlight, examples for all (validate)
- readme
- unit tests

**Comment by trinker** [comment]
Output is not the same.  I suspect this is a result of not normalizing case

**Comment by trinker** [comment]
- figure out difference in output
- Figure out error in Examples https://api.travis-ci.org/jobs/259081813/log.txt?deansi=true
- MAke character warning only on larger number of elements

**Comment by trinker** [comment]
Now only do warning on > 1000 rows or max nchar > 25,000
