### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by emillykkejensen** [trinker/sentimentr#55]
Is there anyway I can use sentimentr with non-english languages?

**Comment by trinker** [comment]
No.  This algorithm is English based.  If you want a simple dictionary lookup I'd suggest tidytext package. It won't take negators, amplifiers and such into consideration but it should should work with a custom dictionaries provided you have a sentiment dictionary for that language

**Comment by emillykkejensen** [comment]
Have worked with other sentiment packages and they are definitely okay, but have had a good eye to this package for some time as I really would like to use some of its functions – just in Danish. What would it take to make it work with eg. Danish?

**Comment by trinker** [comment]
It would take someone who understands Danish, English, and my R code.  I make assumptions about language structures that are English based...I don't know if these assumptions are tenable across other languages.  My guess is some languages yes, others, no.
