### ISSUE TITLE
A straight negative sentence getting positive score

### ISSUE THREAD

**Issue by amrrs** [trinker/sentimentr#58]
Hi, Thanks for the reply in the other issue. keeping this separate since it's a different case.
```

> "Not enough money and poor life" %>% sentiment() 
   element_id sentence_id word_count  sentiment
1:          1           1          6 0.06123724
```

Not sure what's going wrong here. Could you please help. 

Thanks

**Comment by trinker** [comment]
It's the window around your two polarized words:

```
"Not word word enough money and poor life" %>% 
     extract_sentiment_terms()

##    element_id sentence_id    negative positive
## 1:          1           1 enough,poor    money

"Not word word enough money and poor life" %>% 
    sentiment(n.before = 4) 
```

It may be useful if you spend some time reading the README if you haven't yet and looking at the hyperparameters and what they do.  There there's a tradeoff in the hyperparameters that you have to decide that if on average, this model is right more often than it is wrong.  For example, you may set the window function to have 2 words before, and in this case the algorithm will return the correct result.  However, it is likely to return wrong results not for other statements.

**Comment by trinker** [comment]
@amrrs I think that you bring up a point that the clause for the poor life does not include the not.  There should be a way to break the window function at the and.  See here for this suggested change: https://github.com/trinker/sentimentr/issues/59

This will likely be incorporated in the future.

**Comment by amrrs** [comment]
Thanks very much for the response. For now, I'm replacing all my `and` with `,`. That seems like quick fix, Please correct me if i'm wrong. Meanwhile I stumbled upon another FP and bringing it to your notice.
```

> "i was incredibly unhappy" %>% sentiment()
   element_id sentence_id word_count sentiment
1:          1           1          4     0.025
```

**Comment by amrrs** [comment]
@trinker Any response for the above sentence?

**Comment by trinker** [comment]
I am updating the jockers lexicon and removing incredible and then adding it to the valence shifters

**Comment by trinker** [comment]
You can install the latest lexicon package by:

```
library(devtools)
install_github('trinker/lexicon')

library(sentiment); library(dplyr)
"i was incredibly unhappy" %>% sentiment()
##    element_id sentence_id word_count sentiment
## 1:          1           1          4    -0.375
```
