### ISSUE TITLE
Consider adding adversative conjunctions to the comma loc and making formal argument

### ISSUE THREAD

**Issue by trinker** [trinker/sentimentr#59]
Currently commas colons, and semicolons cause the window around a poalrized word to break/stop.  For example:

```
"I have hate; it's not nice"
```

So for hate the window after is zero because the `;` stops the right side window.  Internally this is done via:

```
word_dat[, `:=`(comma_loc, ifelse(words %in% c(";", ":",  ","), comma_loc, NA))]
```

That's good, it breaks the clause.  But adversative conjunctions break clauses too.  So this can happen:

```
> "Not enough money and poor life" %>% sentiment() 
   element_id sentence_id word_count  sentiment
1:          1           1          6 0.06123724
```
https://github.com/trinker/sentimentr/issues/58

Positive?  Sure we can control with the window function be it seems that the left side of the window  for `"poor"` should stop at the `"and"`.  It'd be nice to bring the comma locs outside, maybe called `cluase.breaks` and allow the user to set this or convert on determine on it's own internally if set to `NULL` (default).

**Comment by amrrs** [comment]
Thanks very much for the response. For now, I'm replacing all my `and` with `,`. That seems like quick fix, Please correct me if i'm wrong. Meanwhile I stumbled upon another FP and bringing it to your notice.
```

> "i was incredibly unhappy" %>% sentiment()
   element_id sentence_id word_count sentiment
1:          1           1          4     0.025
```

**Comment by trinker** [comment]
I have added `cluase.breaks` as an argument with the defualt of  `c(";", ":",  ",", "but")` but did not add other conjunctions as they appear to have little efect or a negative effect on accuracy.  That means that in cases like https://github.com/trinker/sentimentr/issues/58 

```
"Not enough money and poor life" %>% sentiment()
```

the algorithm will, by default, find the statement positive.  If the user wishes to add `and` they may do so but it may lower accuracy.

**Comment by trinker** [comment]
This was an ill attemted venture that leads to problems with adversative conjunctions.  This feature has been removed.
