### ISSUE TITLE
Problems with encoding

### ISSUE THREAD

**Issue by johanneswaage** [trinker/sentimentr#74]
Hi,
I have a problem with using a custom polarity and valence shift lexica containing non-english characters (danish characters ø,æ and å). sentiment_by() scores words correctly without special characters, but all words with special characters are scored as 0. All my character vectors are encoded in UTF-8.

Best regards,
Johannes

**Comment by johanneswaage** [comment]
After debugging, looks like the problem is in utils.R:

```r
make_sentence_df2 <- function(sents){

    indx <- wc <- NULL

    ids <- add_row_id(sents)
    text.var <- gsub("[^a-z',;: ]|\\d:\\d|\\d ", " ", 
        stringi::stri_trans_tolower(gsub("(\\s*)([;:,]+)", " \\2", unlist(sents)))
    )
    dat <- data.frame(
        id = ids,
        sentences = text.var,
    	  wc = count_words(text.var),
        stringsAsFactors = FALSE
    )
    data.table::setDT(dat)
    dat[, indx:= wc < 1, by=c('id', 'sentences', 'wc')][(indx), c('sentences', 'wc'):=NA][, 
        indx:=NULL][]
}
```

The gsub-statement only keeps english characters. A solution for danish characters could be 

```r
text.var <- gsub("[^a-zøæå',;: ]|\\d:\\d|\\d ", " ", 
        stringi::stri_trans_tolower(gsub("(\\s*)([;:,]+)", " \\2", unlist(sents)))
    )
```
but we probably need something more general.
/J

**Comment by trinker** [comment]
sentimentr is designed for English...it is unsupported for other languages.  The language model that sentimentr is based on assumes an English grammatical structure.  Unless you're certain that Danish and English are grammatically identical with regard to positioning of valence shifters and polarized words this violates the underlying assumptions of the model and the results can not be trusted.

I think that another sentiment package may be more appropriate.  The readme of the sentimentr package details some of these approaches (including benchmarking on speed and accuracy).  Most are a simple hash lookup and, while less accurate on English, are generalizable to other languages.  The tidytext package also supports a more hands on analysis that would give you the freedom and flexibility to handle whatever language you wish.

I'm going to make the English language model assumption more prominent in the package description.

**Comment by johanneswaage** [comment]
Thanks for your answer. English and Danish are both germanic languages, so by far and large the approach applied in sentimentr is applicable to Danish as well, and the valence modification approach is exactly what makes it stand apart from other packages, with some tweaking to the parameters n.before and n.after. Swedish and Norwegian could also benefit here.
I'll create a local modified fork, thanks.
/J

**Comment by trinker** [comment]
@johanneswaage I have never worked with these other languages.  This may mean sentimentr could have broader application than it was designed for.  It seems with some work the commas could be expanded to be more generalizable based on what you showed above all without violating the underlying language model.

**Comment by trinker** [comment]
@johanneswaage Did you ever do any work on this?

**Comment by trinker** [comment]
Closing as no further interest was shown
