### ISSUE TITLE
Error in left_just(data.frame(stanford = sentiment_stanford(ase)[["sentiment"]],  :    could not find function "left_just"

### ISSUE THREAD

**Issue by isathish** [trinker/sentimentr#76]
Error in left_just(data.frame(stanford = sentiment_stanford(ase)[["sentiment"]],  : 
  could not find function "left_just"

**Comment by trinker** [comment]
Hi thanks for posting.  Where is that code coming from.?

**Comment by trinker** [comment]
A quick search of the repo reveals this is in the README.  A few lines before that is:

```
if (!require("pacman")) install.packages("pacman")
pacman::p_load_gh("trinker/sentimentr", "trinker/stansent", "sfeuerriegel/SentimentAnalysis", "wrathematics/meanr")
pacman::p_load(syuzhet, qdap, microbenchmark, RSentiment)
```

This installs qdap which has the `left_just` function.  Did you run this?  If you did, qdap is either loaded or the `p_load` threw a warning or error. The error you get indicates you didn't run this code or it threw a warning/error.  In any event we need more information to debug this.
