### ISSUE TITLE
German vowels ä, ö ü and sharp s/eszett ß

### ISSUE THREAD

**Issue by Matthias2018** [trinker/sentimentr#79]
It seems that the line of code don’t accept german vowels ä, ö, ü and not grapheme ß (Eszett or sharp s) as well. I can read in lexicon and shifters as UTF-8 without any problems and can work with text without vowels and sharp s. The sentiment values are correct in these cases. If I have text with the four letters typical for the German language sentiment-function obviously don’t recognize the words.

There is a possible workaround of course: I can substitute all ä, ö, ü and ß with ae, oe, ue and ss. But this is not an elegant solution because if one need vowels and eszett/sharp s in analytical steps prior to sentiment analysis or after one can only undo the transformation partially. Another solution is to work with sentiments on a separate corpus especially prepared for this analysis and use the original one for other analyses. Also not very attractive. 

Perhaps I missed something in the code/functions and would appreciate any advice.

A second challenge with german language: German verbs are objects to sometimes extensive conjunctions (simple example: sich beschweren = complain, er beschwerte sich = he complained). Before choosing stemming a major part of these and similar problems (with adjectives and nouns) can be solved by wildcards (*). As far as I can see this is not a choice at the moment.

**Comment by trinker** [comment]
I believe these issues are connected: https://github.com/trinker/sentimentr/issues/74

**Comment by Matthias2018** [comment]
Yes, issues #79 and #74 are closely linked. A solution is likely to lie in the extension of characters via gsub in sentimentr / R / utils.R, as johanneswaage has suggested.

**Comment by trinker** [comment]
As I discuss here (https://github.com/trinker/sentimentr/issues/74#issuecomment-361955888) sentimentr is English based.  I don't have the expertise in other languages to understand the ramifications of of extending it beyond it's current state.
