### ISSUE TITLE
Same algorithm as in qdap's polarity function?

### ISSUE THREAD

**Issue by Lucinho91** [trinker/sentimentr#82]
Dear Mr. Rinker, 

first of all thank you for your very helpful packages for text mining and sentiment analysis! I use them a lot and so you helped me so much with my master's thesis!

One question considering the algorithm of the "sentiment"-function: Is this the same approach used by qdap's "polarity"-function? If so, did I understand correctly that the difference is that "sentiment"-function can incorporate other dictionaries besides Hu & Liu (2004)? Anyways, your lexicon-based approach to sentiment analysis is very clever and I really like how you managed to include valence shifters, great work! 

Thank you and best regards from Germany!

**Comment by trinker** [comment]
> One question considering the algorithm of the "sentiment"-function: Is this the same approach used by qdap's "polarity"-function? If so, did I understand correctly that the difference is that "sentiment"-function can incorporate other dictionaries besides Hu & Liu (2004)? Anyways, your lexicon-based approach to sentiment analysis is very clever and I really like how you managed to include valence shifters, great work!

It is built from qdap's `polarity` but improved.  Same basic idea though.  qdap could also take other dictionaries but in the **sentimentr** package I have designed this process to be easier and there are ready to go dictionaries provided in the **lexicon** package already.
